# ~/.config/starship.toml

# Disable the newline at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are confguring is "character"
symbol = "âœ "     # The "symbol" segment is being set to "âœ"

# this shows only when the devise's battery is under 10%
[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

# Git branch module
[git_branch]
symbol = "ğŸ‚ "

# Git status
[git_status]
disabled = true

