# ~/.config/starship.toml

# Disable the newline at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are confguring is "character"
symbol = "âœ "     # The "symbol" segment is being set to "âœ"

# Git status
[git_status]
disabled = false
style = "bold green"
conflicted = "ğŸ³ "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[git_branch]
symbol = "ğŸŒ± "

[aws]
symbol = "â›… "

[golang]
symbol = "ğŸš€ "

[hostname]
prefix = "âŸª"
suffix = "âŸ«"

[java]
symbol = "â˜• "

[python]
symbol = "ğŸ "

[ruby]
symbol = "â˜ª "

[rust]
symbol = "âš™ï¸ "

[time]
disabled = false
format = "ğŸ•™ [ %T ]"
