# Disable the newline at the start of the prompt
add_newline = false

# Git status
[git_status]
disabled = false
style = "bold green"
conflicted = "ğŸ³ "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[git_branch]
symbol = "ğŸŒ± "

[aws]
symbol = "â›… "

[nodejs]
symbol= "ğŸ§¤ "

[golang]
symbol = "ğŸš€ "

[java]
symbol = "â˜• "

[python]
symbol = "ğŸ "

[rust]
symbol = "âš™ï¸  "

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"
